"""Gera game/data/monsters.json e hunts.json com stats reais do Tibia 7.4."""
import json
import os

DATA = "/home/user/tibia-idle/game/data"
ASSETS = "/home/user/tibia-idle/game/assets"
man = json.load(open("%s/manifest.json" % ASSETS))
ITEMS = json.load(open("%s/items.json" % DATA))

# name, hp, exp, dano medio por ataque, armadura, elemento principal
# stats aproximados do Tibia 7.4 real
M = [
    # slug,          nome,               hp,    exp,   dmg, armor, elem
    ("rat",          "Rat",              20,     5,     6,   1, "physical"),
    ("cave-rat",     "Cave Rat",         30,     8,     8,   2, "physical"),
    ("snake",        "Snake",            35,    10,     8,   3, "earth"),
    ("bug",          "Bug",              30,     6,     7,   4, "physical"),
    ("spider",       "Spider",           50,    12,    10,   3, "earth"),
    ("wasp",         "Wasp",             35,    12,    12,   4, "physical"),
    ("scorpion",     "Scorpion",         45,    30,    18,   4, "earth"),
    ("rotworm",      "Rotworm",          65,    40,    20,   5, "physical"),
    ("poison-spider","Poison Spider",    66,    44,    22,   6, "earth"),
    ("goblin",       "Goblin",           60,    25,    18,   5, "physical"),
    ("wolf",         "Wolf",             55,    25,    18,   4, "physical"),
    ("bear",         "Bear",            105,    73,    32,   8, "physical"),
    ("polar-bear",   "Polar Bear",      110,    80,    34,   9, "ice"),
    ("skeleton",     "Skeleton",         50,    35,    22,   8, "death"),
    ("troll",        "Troll",            50,    20,    16,   5, "physical"),
    ("swamp-troll",  "Swamp Troll",      65,    30,    20,   6, "earth"),
    ("frost-troll",  "Frost Troll",      55,    30,    20,   6, "ice"),
    ("orc",          "Orc",              70,    25,    20,   6, "physical"),
    ("orc-spearman", "Orc Spearman",     85,    40,    28,   7, "physical"),
    ("orc-warrior",  "Orc Warrior",     125,    62,    35,  10, "physical"),
    ("orc-shaman",   "Orc Shaman",       60,    70,    30,   5, "energy"),
    ("orc-berserker","Orc Berserker",   210,   195,    60,  14, "physical"),
    ("orc-rider",    "Orc Rider",       180,   110,    45,  12, "physical"),
    ("orc-leader",   "Orc Leader",      270,   270,    70,  18, "physical"),
    ("orc-warlord",  "Orc Warlord",     950,   890,   140,  30, "physical"),
    ("war-wolf",     "War Wolf",        160,    95,    42,  10, "physical"),
    ("ghoul",        "Ghoul",           100,    85,    40,  12, "death"),
    ("minotaur",     "Minotaur",        100,    50,    30,  10, "physical"),
    ("minotaur-archer","Minotaur Archer",100,   100,    45,  10, "physical"),
    ("minotaur-guard","Minotaur Guard", 185,   150,    55,  15, "physical"),
    ("minotaur-mage","Minotaur Mage",   110,   150,    50,   8, "energy"),
    ("cyclops",      "Cyclops",         260,   150,    60,  20, "physical"),
    ("dwarf",        "Dwarf",            90,    45,    28,  12, "physical"),
    ("dwarf-soldier","Dwarf Soldier",   135,    85,    40,  16, "physical"),
    ("dwarf-guard",  "Dwarf Guard",     215,   165,    58,  22, "physical"),
    ("dwarf-geomancer","Dwarf Geomancer",145,  190,    55,  12, "earth"),
    ("elf",          "Elf",              75,    42,    26,   8, "physical"),
    ("elf-scout",    "Elf Scout",       120,    85,    40,  10, "physical"),
    ("elf-arcanist", "Elf Arcanist",    175,   225,    62,  10, "energy"),
    ("mummy",        "Mummy",           240,   150,    52,  18, "death"),
    ("demon-skeleton","Demon Skeleton", 200,   240,    65,  20, "death"),
    ("crypt-shambler","Crypt Shambler", 195,   195,    60,  16, "death"),
    ("bonebeast",    "Bonebeast",       515,   580,   105,  30, "death"),
    ("stone-golem",  "Stone Golem",     450,   350,    85,  40, "earth"),
    ("gargoyle",     "Gargoyle",        250,   150,    58,  30, "earth"),
    ("scarab",       "Scarab",          340,   240,    72,  28, "earth"),
    ("ancient-scarab","Ancient Scarab", 800,   750,   130,  35, "earth"),
    ("larva",        "Larva",           170,   130,    48,  12, "earth"),
    ("cobra",        "Cobra",           100,    75,    38,   8, "earth"),
    ("witch",        "Witch",           300,   340,    75,  15, "earth"),
    ("monk",         "Monk",            240,   200,    62,  20, "holy"),
    ("priestess",    "Priestess",       290,   350,    78,  14, "death"),
    ("bonelord",     "Bonelord",        260,   260,    68,  20, "energy"),
    ("elder-bonelord","Elder Bonelord", 500,   500,    98,  25, "energy"),
    ("gazer",        "Gazer",           125,   100,    42,  10, "energy"),
    ("slime",        "Slime",           160,     0,    45,   5, "earth"),
    ("giant-spider", "Giant Spider",    900,   900,   140,  30, "earth"),
    ("vampire",      "Vampire",         475,   305,    88,  30, "death"),
    ("banshee",      "Banshee",         550,   580,   105,  25, "death"),
    ("ghost",        "Ghost",           150,   250,    62,  20, "death"),
    ("hero",         "Hero",           1400,  1200,   175,  35, "physical"),
    ("black-knight", "Black Knight",   1400,  1000,   165,  38, "physical"),
    ("necromancer",  "Necromancer",     580,   580,   110,  22, "death"),
    ("green-djinn",  "Green Djinn",     800,   750,   130,  25, "earth"),
    ("blue-djinn",   "Blue Djinn",      800,   750,   130,  25, "ice"),
    ("efreet",       "Efreet",         1650,  1750,   205,  35, "fire"),
    ("marid",        "Marid",          1650,  1750,   205,  35, "ice"),
    ("fire-devil",   "Fire Devil",      400,   250,    72,  15, "fire"),
    ("fire-elemental","Fire Elemental", 550,   500,   100,  20, "fire"),
    ("winter-wolf",  "Winter Wolf",     160,   100,    42,  12, "ice"),
    ("yeti",         "Yeti",            800,   700,   125,  25, "ice"),
    ("quara-predator","Quara Predator",1000,  1000,   150,  30, "ice"),
    ("pirate-marauder","Pirate Marauder",300,  250,    70,  20, "physical"),
    ("pirate-cutthroat","Pirate Cutthroat",400, 400,    88,  25, "physical"),
    ("pirate-buccaneer","Pirate Buccaneer",550, 550,   105,  28, "physical"),
    ("pirate-corsair","Pirate Corsair", 700,   800,   125,  32, "physical"),
    ("lich",         "Lich",            880,   900,   140,  30, "death"),
    ("dragon",       "Dragon",         1000,   700,   130,  25, "fire"),
    ("dragon-lord",  "Dragon Lord",    1900,  2100,   210,  35, "fire"),
    ("demon",        "Demon",          8200,  6000,   400,  45, "fire"),
    ("behemoth",     "Behemoth",       3000,  2500,   250,  45, "physical"),
    ("hyaena",       "Hyaena",          200,   120,    45,  12, "physical"),
    ("lion",         "Lion",            170,   120,    45,  12, "physical"),
    ("badger",       "Badger",           40,    10,    10,   3, "physical"),
    ("deer",         "Deer",             35,    12,     8,   3, "physical"),
    ("rabbit",       "Rabbit",           15,     2,     3,   1, "physical"),
    ("pig",          "Pig",              25,     4,     5,   2, "physical"),
    ("sheep",        "Sheep",            20,     3,     4,   1, "physical"),
    ("dog",          "Dog",              25,     5,     6,   2, "physical"),
    ("mimic",        "Mimic",          1000,  1200,   150,  35, "physical"),
    ("butterfly",    "Butterfly",         5,     1,     1,   0, "physical"),
]

# ---------------------------------------------------------------- LOOT
# (item, chance %, quantidade max) — loot table proxima do Tibia real
LOOT = {
    "rat": [("gold-coin", 60, 4), ("cheese", 15, 1)],
    "cave-rat": [("gold-coin", 70, 8), ("cheese", 12, 1)],
    "snake": [("gold-coin", 40, 5)],
    "bug": [("gold-coin", 35, 4)],
    "spider": [("gold-coin", 50, 8)],
    "wasp": [("gold-coin", 45, 6)],
    "scorpion": [("gold-coin", 65, 12)],
    "rotworm": [("gold-coin", 70, 20), ("meat", 20, 1), ("ham", 12, 1)],
    "poison-spider": [("gold-coin", 65, 15)],
    "goblin": [("gold-coin", 70, 15), ("small-axe", 6, 1), ("bone-club", 5, 1),
               ("leather-helmet", 5, 1)],
    "wolf": [("gold-coin", 55, 10), ("meat", 25, 1)],
    "bear": [("gold-coin", 60, 20), ("ham", 30, 1), ("meat", 20, 2)],
    "polar-bear": [("gold-coin", 60, 25), ("ham", 30, 1)],
    "skeleton": [("gold-coin", 70, 15), ("bone", 30, 1), ("sword", 5, 1),
                 ("brass-shield", 4, 1), ("viking-helmet", 3, 1)],
    "troll": [("gold-coin", 65, 15), ("leather-boots", 8, 1),
              ("spear", 8, 1), ("hand-axe", 6, 1)],
    "swamp-troll": [("gold-coin", 65, 20), ("club", 8, 1), ("meat", 15, 1)],
    "frost-troll": [("gold-coin", 60, 20), ("fish", 20, 1), ("club", 6, 1)],
    "orc": [("gold-coin", 70, 20), ("axe", 6, 1), ("studded-shield", 5, 1)],
    "orc-spearman": [("gold-coin", 70, 25), ("spear", 20, 3),
                     ("studded-armor", 6, 1)],
    "orc-warrior": [("gold-coin", 75, 35), ("axe", 8, 1), ("chain-armor", 6, 1),
                    ("brass-helmet", 5, 1)],
    "orc-shaman": [("gold-coin", 70, 25), ("wooden-wand", 8, 1),
                   ("green-tunic", 6, 1)],
    "orc-berserker": [("gold-coin", 80, 60), ("double-axe", 8, 1),
                      ("brass-armor", 8, 1), ("chain-helmet", 6, 1)],
    "orc-rider": [("gold-coin", 75, 45), ("scale-armor", 7, 1),
                  ("orcish-axe", 6, 1)],
    "orc-leader": [("gold-coin", 85, 90), ("plate-shield", 8, 1),
                   ("orcish-axe", 8, 1), ("chain-armor", 8, 1)],
    "orc-warlord": [("gold-coin", 95, 200), ("plate-armor", 12, 1),
                    ("great-axe", 3, 1), ("dwarven-shield", 6, 1),
                    ("knight-axe", 5, 1)],
    "war-wolf": [("gold-coin", 65, 30), ("meat", 25, 2)],
    "ghoul": [("gold-coin", 70, 35), ("bone", 30, 1),
              ("torch", 15, 1), ("ham", 12, 1)],
    "minotaur": [("gold-coin", 75, 25), ("mace", 8, 1), ("chain-armor", 6, 1),
                 ("brass-helmet", 5, 1), ("ham", 15, 1)],
    "minotaur-archer": [("gold-coin", 75, 35), ("bow", 8, 1), ("arrow", 40, 12),
                        ("chain-armor", 6, 1)],
    "minotaur-guard": [("gold-coin", 80, 50), ("battle-shield", 8, 1),
                       ("chain-helmet", 8, 1), ("mace", 8, 1)],
    "minotaur-mage": [("gold-coin", 75, 40), ("wooden-wand", 8, 1),
                      ("mystic-turban", 4, 1)],
    "cyclops": [("gold-coin", 80, 60), ("battle-hammer", 6, 1),
                ("plate-shield", 6, 1), ("ham", 25, 2), ("club-ring", 2, 1)],
    "dwarf": [("gold-coin", 75, 30), ("pick", 10, 1), ("hatchet", 8, 1),
              ("dwarven-shield", 4, 1)],
    "dwarf-soldier": [("gold-coin", 75, 45), ("chain-armor", 8, 1),
                      ("sabre", 8, 1), ("dwarven-shield", 5, 1)],
    "dwarf-guard": [("gold-coin", 80, 70), ("dwarven-shield", 8, 1),
                    ("battle-hammer", 6, 1), ("plate-armor", 3, 1)],
    "dwarf-geomancer": [("gold-coin", 80, 60), ("wand-of-might", 3, 1),
                        ("dwarven-ring", 5, 1), ("small-diamond", 2, 1)],
    "elf": [("gold-coin", 70, 25), ("bow", 6, 1), ("arrow", 35, 10),
            ("elven-amulet", 3, 1)],
    "elf-scout": [("gold-coin", 75, 40), ("bow", 8, 1), ("arrow", 40, 15),
                  ("elven-amulet", 4, 1), ("elven-brooch", 3, 1)],
    "elf-arcanist": [("gold-coin", 80, 60), ("elven-wand", 6, 1),
                     ("elven-amulet", 6, 1), ("blue-robe", 2, 1)],
    "mummy": [("gold-coin", 80, 60), ("bone", 30, 1), ("silver-brooch", 6, 1),
              ("strange-talisman", 5, 1), ("silver-necklace", 4, 1)],
    "demon-skeleton": [("gold-coin", 80, 70), ("bone", 30, 1),
                       ("battle-shield", 6, 1), ("morning-star", 6, 1),
                       ("iron-helmet", 4, 1)],
    "crypt-shambler": [("gold-coin", 80, 60), ("bone", 40, 2),
                       ("morning-star", 6, 1), ("brass-armor", 5, 1)],
    "bonebeast": [("gold-coin", 85, 110), ("big-bone", 25, 1),
                  ("bone-shield", 8, 1), ("scarab-shield", 4, 1),
                  ("bone-sword", 5, 1)],
    "stone-golem": [("gold-coin", 85, 90), ("small-diamond", 3, 1),
                    ("stone-skin-amulet", 3, 1), ("iron-ore", 0, 1),
                    ("piece-of-iron", 12, 1)],
    "gargoyle": [("gold-coin", 80, 55), ("bone-shield", 6, 1),
                 ("stone-skin-amulet", 3, 1)],
    "scarab": [("gold-coin", 80, 70), ("scarab-coin", 20, 2),
               ("scarab-shield", 4, 1), ("scarab-amulet", 4, 1)],
    "ancient-scarab": [("gold-coin", 88, 130), ("scarab-coin", 40, 4),
                       ("scarab-shield", 8, 1), ("holy-scarab", 8, 1),
                       ("small-diamond", 3, 1)],
    "larva": [("gold-coin", 75, 40), ("scarab-coin", 12, 1)],
    "cobra": [("gold-coin", 70, 35), ("cobrafang-dagger", 3, 1)],
    "witch": [("gold-coin", 80, 70), ("blank-rune", 12, 2),
              ("mysterious-fetish", 8, 1), ("cape", 8, 1),
              ("silver-dagger", 3, 1), ("star-herb", 10, 1)],
    "monk": [("gold-coin", 78, 55), ("cowl", 10, 1), ("sandals", 10, 1),
             ("scroll", 0, 1), ("book", 8, 1)],
    "priestess": [("gold-coin", 82, 70), ("blank-rune", 12, 2),
                  ("necrotic-rod", 0, 1), ("cape", 8, 1),
                  ("voodoo-doll", 5, 1)],
    "bonelord": [("gold-coin", 80, 60), ("beholder-shield", 5, 1),
                 ("small-emerald", 3, 1), ("bone", 20, 1)],
    "elder-bonelord": [("gold-coin", 85, 100), ("beholder-shield", 8, 1),
                       ("small-emerald", 5, 1), ("great-shield", 1, 1)],
    "gazer": [("gold-coin", 75, 45), ("bone", 20, 1), ("beholder-shield", 3, 1)],
    "slime": [("gold-coin", 40, 20), ("vial", 25, 1)],
    "giant-spider": [("gold-coin", 90, 130), ("plate-shield", 8, 1),
                     ("time-ring", 4, 1), ("spike-sword", 5, 1),
                     ("knight-legs", 3, 1), ("platinum-amulet", 2, 1)],
    "vampire": [("gold-coin", 85, 90), ("vampire-shield", 3, 1),
                ("black-pearl", 8, 1), ("strange-symbol", 4, 1),
                ("skull", 15, 1)],
    "banshee": [("gold-coin", 85, 110), ("silver-necklace", 8, 1),
                ("elven-amulet", 6, 1), ("blue-robe", 2, 1),
                ("crystal-necklace", 4, 1)],
    "ghost": [("gold-coin", 70, 40), ("morning-star", 5, 1),
              ("mysterious-fetish", 5, 1)],
    "hero": [("gold-coin", 92, 200), ("crown-armor", 3, 1),
             ("crown-legs", 3, 1), ("crown-helmet", 3, 1),
             ("crown-shield", 3, 1), ("boots-of-haste", 2, 1),
             ("fire-sword", 3, 1), ("small-diamond", 5, 2)],
    "black-knight": [("gold-coin", 90, 180), ("dark-armor", 8, 1),
                     ("dark-helmet", 8, 1), ("dark-shield", 8, 1),
                     ("mystic-turban", 4, 1), ("crown-armor", 2, 1)],
    "necromancer": [("gold-coin", 85, 100), ("skull-staff", 4, 1),
                    ("boots-of-haste", 1, 1), ("blank-rune", 15, 3),
                    ("silver-amulet", 6, 1), ("skull", 20, 1)],
    "green-djinn": [("gold-coin", 88, 130), ("green-tunic", 8, 1),
                    ("mystic-turban", 6, 1), ("small-emerald", 6, 1),
                    ("small-oil-lamp", 8, 1), ("green-gem", 1, 1)],
    "blue-djinn": [("gold-coin", 88, 130), ("blue-robe", 4, 1),
                   ("mystic-turban", 6, 1), ("small-sapphire", 6, 1),
                   ("blue-gem", 1, 1)],
    "efreet": [("gold-coin", 92, 220), ("small-emerald", 10, 2),
               ("green-gem", 3, 1), ("magic-sword", 0, 1),
               ("mystic-turban", 10, 1), ("elven-amulet", 8, 1)],
    "marid": [("gold-coin", 92, 220), ("small-sapphire", 10, 2),
              ("blue-gem", 3, 1), ("blue-robe", 6, 1),
              ("mystic-turban", 10, 1)],
    "fire-devil": [("gold-coin", 80, 65), ("torch", 25, 1),
                   ("small-ruby", 3, 1)],
    "fire-elemental": [("gold-coin", 82, 80), ("small-ruby", 5, 1),
                       ("burning-heart", 4, 1)],
    "winter-wolf": [("gold-coin", 70, 35), ("meat", 25, 2)],
    "yeti": [("gold-coin", 88, 120), ("ham", 30, 3), ("dirty-fur", 20, 1),
             ("small-sapphire", 4, 1)],
    "quara-predator": [("gold-coin", 88, 150), ("shrimp", 25, 3),
                       ("small-sapphire", 5, 1), ("northern-pike", 20, 2)],
    "pirate-marauder": [("gold-coin", 80, 70), ("sabre", 8, 1),
                        ("compass", 0, 1), ("rum-flask", 0, 1)],
    "pirate-cutthroat": [("gold-coin", 82, 90), ("sabre", 8, 1),
                         ("scale-armor", 6, 1), ("dagger", 8, 1)],
    "pirate-buccaneer": [("gold-coin", 85, 110), ("plate-armor", 4, 1),
                         ("epee", 5, 1), ("brass-legs", 6, 1)],
    "pirate-corsair": [("gold-coin", 88, 140), ("plate-armor", 6, 1),
                       ("epee", 6, 1), ("golden-mug", 5, 1),
                       ("small-ruby", 4, 1)],
    "lich": [("gold-coin", 90, 160), ("platinum-amulet", 3, 1),
             ("small-diamond", 6, 1), ("skull-staff", 3, 1),
             ("gold-ring", 4, 1), ("blank-rune", 15, 3)],
    "dragon": [("gold-coin", 92, 110), ("dragon-ham", 40, 2),
               ("dragon-shield", 3, 1), ("steel-shield", 8, 1),
               ("dragon-scale-mail", 1, 1), ("burst-arrow", 12, 8),
               ("small-diamond", 3, 1), ("serpent-sword", 4, 1)],
    "dragon-lord": [("gold-coin", 95, 250), ("dragon-ham", 50, 4),
                    ("dragon-shield", 6, 1), ("dragon-scale-mail", 3, 1),
                    ("royal-helmet", 2, 1), ("golden-armor", 1, 1),
                    ("small-diamond", 8, 2), ("life-crystal", 4, 1)],
    "demon": [("gold-coin", 98, 400), ("demon-shield", 3, 1),
              ("demon-helmet", 2, 1), ("golden-legs", 1, 1),
              ("magic-plate-armor", 1, 1), ("fire-axe", 4, 1),
              ("might-ring", 6, 1), ("small-ruby", 12, 3),
              ("giant-sword", 4, 1), ("platinum-amulet", 4, 1),
              ("ring-of-healing", 4, 1)],
    "behemoth": [("gold-coin", 95, 300), ("great-axe", 2, 1),
                 ("crown-legs", 3, 1), ("small-diamond", 8, 2),
                 ("stone-skin-amulet", 4, 1), ("piece-of-iron", 20, 2)],
    "hyaena": [("gold-coin", 65, 30), ("meat", 25, 1)],
    "lion": [("gold-coin", 65, 30), ("meat", 25, 1)],
    "badger": [("gold-coin", 40, 8)],
    "deer": [("gold-coin", 35, 8), ("meat", 30, 1)],
    "rabbit": [("meat", 40, 1)],
    "pig": [("gold-coin", 30, 6), ("meat", 35, 1)],
    "sheep": [("gold-coin", 25, 5), ("meat", 30, 1)],
    "dog": [("gold-coin", 30, 6), ("meat", 25, 1)],
    "mimic": [("gold-coin", 90, 180), ("small-diamond", 8, 2),
              ("crystal-necklace", 6, 1), ("golden-mug", 8, 1)],
    "butterfly": [],
}

monsters = {}
for slug, name, hp, exp, dmg, armor, elem in M:
    loot = []
    for it, chance, cnt in LOOT.get(slug, []):
        if it not in ITEMS or chance <= 0:
            continue
        loot.append({"item": it, "chance": chance, "max": cnt})
    monsters[slug] = {
        "name": name, "hp": hp, "exp": exp, "damage": dmg,
        "armor": armor, "element": elem, "loot": loot,
        # velocidade de ataque em ms (bichos rapidos batem mais)
        "attackSpeed": 2000,
    }

json.dump(monsters, open("%s/monsters.json" % DATA, "w"), indent=1)
print("monstros:", len(monsters))
missing = [s for s, *_ in M
           if not os.path.exists("%s/mob/%s_s.png" % (ASSETS, s))]
print("sem sprite:", missing)
